version: '3'
services:
  scrap-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app/app
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
