version: '3'
services:
  scrap-api:
    environment:
      - PT_ENV=${PT_ENV}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - LOCATION_IQ_API_KEY=${LOCATION_IQ_API_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app/app
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
